name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Lint
        run: echo "Lint step"

      - name: Test
        run: mvn -f devops-assessment-java/pom.xml test

      - name: Build
        run: mvn -f devops-assessment-java/pom.xml clean install

      - name: Deploy
        run: echo "Deploy step"
